export const citiesObject = [
  {
    id: 1,
    name: 'Vladivostok',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 2,
    name: 'Moscow',
    postalCode: 101,
    logo: '/assets/1.png',
  },
  {
    id: 3,
    name: 'Saint-Petersburg',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 4,
    name: 'Khabarovsk',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 5,
    name: 'Kazyan',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 6,
    name: 'Kaluga',
    postalCode: 248,
    logo: '/assets/1.png',
  },
  {
    id: 7,
    name: 'Magadan',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 8,
    name: 'Nakhodka',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 9,
    name: 'Artem',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 10,
    name: 'Ussuriysk',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 11,
    name: 'Ternei',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 12,
    name: 'Murmansk',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 13,
    name: 'Ufa',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 14,
    name: 'Novosibirsk',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 15,
    name: 'Ekaterinburg',
    postalCode: 453,
    logo: '/assets/1.png',
  },
  {
    id: 16,
    name: 'Bryansk',
    postalCode: 100,
    logo: '/assets/1.png',
  },
  {
    id: 17,
    name: 'Ulan-Ude',
    postalCode: 4566,
    logo: '/assets/1.png',
  },
  {
    id: 18,
    name: 'Tomsk',
    postalCode: 123,
    logo: '/assets/1.png',
  },
  {
    id: 19,
    name: 'Berlin',
    postalCode: 2345,
    logo: '/assets/1.png',
  },
  {
    id: 20,
    name: 'Kalina',
    postalCode: 128,
    logo: '/assets/1.png',
  },
];
